name: Release (main)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release_main:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run check
      - run: bun run test
      - run: bun run build
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          manifest-file: .release-manifest.json
          config-file: release.json
      - name: Setup NPM
        if: ${{ steps.release.outputs.release_created }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm config set registry=https://registry.npmjs.org/
      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        working-directory: dist
        run: npm publish --access public --provenance
