name: Release (main)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml

  release_main:
    name: Build & Release
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          config-file: release.json
